apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowrie
  labels:
    app: cowrie
  namespace: kube-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowrie
  template:
    metadata:
      labels:
        app: cowrie
    spec:
      containers:
        - name: cowrie
          image: acrworkflow1698624409294.azurecr.io/image-workflow-1698624409294:latest
          ports:
            - containerPort: 8000