apiVersion: v1
kind: Service
metadata:
  name: cowrie
  namespace: kube-public
spec:
  type: LoadBalancer
  selector:
    app: cowrie
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000